## Input Data Schema

# feature id: feature name
# The order must be consistent with the raw data.
# First field is the label. Case insensitive here.
1: label
2: user_id
3: listing_id
4: due_amt
5: due_date_day
6: default_amt_max
7: default_amt_mean
8: default_amt_min
9: default_times
10: default_times_pct
11: first_prepay_days_max
12: first_prepay_days_mean
13: first_prepay_days_min
14: first_prepay_days_mode
15: first_prepay_due_amt_max
16: first_prepay_due_amt_mean
17: first_prepay_due_amt_min
18: max_continue_repay_times_once
19: mean_coninue_repay_times_once
20: normal_amt_max
21: normal_amt_mean
22: normal_amt_min
23: normal_times
24: normal_times_pct
25: prepay_days_max
26: prepay_days_mean
27: prepay_days_mode
28: prepay_time
29: prepay_time_pct
30: weighted_amt_max
31: weighted_amt_mean
32: weighted_amt_min
33: last_12_bhmonth_type1_cnt
34: last_12_bhmonth_type1_dawn_click_pct
35: last_12_bhmonth_type1_max_click_cnt_day
36: last_12_bhmonth_type1_max_cnt_day
37: last_12_bhmonth_type1_max_cnt_day_dawn
38: last_12_bhmonth_type1_max_cnt_hour
39: last_12_bhmonth_type1_mean_cnt_day
40: last_12_bhmonth_type1_mean_cnt_day_dawn
41: last_12_bhmonth_type1_mean_cnt_hour
42: last_12_bhmonth_type1_min_cnt_day
43: last_12_bhmonth_type1_std_cnt_day
44: last_12_bhmonth_type1_std_cnt_day_dawn
45: last_12_bhmonth_type1_std_cnt_hour
46: last_12_bhmonth_type23_cnt
47: last_12_bhmonth_type23_dawn_click_pct
48: last_12_bhmonth_type23_max_click_cnt_day
49: last_12_bhmonth_type23_max_cnt_day
50: last_12_bhmonth_type23_max_cnt_day_dawn
51: last_12_bhmonth_type23_max_cnt_hour
52: last_12_bhmonth_type23_mean_cnt_day
53: last_12_bhmonth_type23_mean_cnt_day_dawn
54: last_12_bhmonth_type23_mean_cnt_hour
55: last_12_bhmonth_type23_min_cnt_day
56: last_12_bhmonth_type23_std_cnt_day
57: last_12_bhmonth_type23_std_cnt_day_dawn
58: last_12_bhmonth_type23_std_cnt_hour
59: last_1_bhmonth_type1_cnt
60: last_1_bhmonth_type1_dawn_click_pct
61: last_1_bhmonth_type1_max_click_cnt_day
62: last_1_bhmonth_type1_max_cnt_day
63: last_1_bhmonth_type1_max_cnt_day_dawn
64: last_1_bhmonth_type1_max_cnt_hour
65: last_1_bhmonth_type1_mean_cnt_day
66: last_1_bhmonth_type1_mean_cnt_day_dawn
67: last_1_bhmonth_type1_mean_cnt_hour
68: last_1_bhmonth_type1_min_cnt_day
69: last_1_bhmonth_type1_std_cnt_day
70: last_1_bhmonth_type1_std_cnt_day_dawn
71: last_1_bhmonth_type1_std_cnt_hour
72: last_1_bhmonth_type23_cnt
73: last_1_bhmonth_type23_dawn_click_pct
74: last_1_bhmonth_type23_max_click_cnt_day
75: last_1_bhmonth_type23_max_cnt_day
76: last_1_bhmonth_type23_max_cnt_day_dawn
77: last_1_bhmonth_type23_max_cnt_hour
78: last_1_bhmonth_type23_mean_cnt_day
79: last_1_bhmonth_type23_mean_cnt_day_dawn
80: last_1_bhmonth_type23_mean_cnt_hour
81: last_1_bhmonth_type23_min_cnt_day
82: last_1_bhmonth_type23_std_cnt_day
83: last_1_bhmonth_type23_std_cnt_day_dawn
84: last_1_bhmonth_type23_std_cnt_hour
85: last_3_bhmonth_type1_cnt
86: last_3_bhmonth_type1_dawn_click_pct
87: last_3_bhmonth_type1_max_click_cnt_day
88: last_3_bhmonth_type1_max_cnt_day
89: last_3_bhmonth_type1_max_cnt_day_dawn
90: last_3_bhmonth_type1_max_cnt_hour
91: last_3_bhmonth_type1_mean_cnt_day
92: last_3_bhmonth_type1_mean_cnt_day_dawn
93: last_3_bhmonth_type1_mean_cnt_hour
94: last_3_bhmonth_type1_min_cnt_day
95: last_3_bhmonth_type1_std_cnt_day
96: last_3_bhmonth_type1_std_cnt_day_dawn
97: last_3_bhmonth_type1_std_cnt_hour
98: last_3_bhmonth_type23_cnt
99: last_3_bhmonth_type23_dawn_click_pct
100: last_3_bhmonth_type23_max_click_cnt_day
101: last_3_bhmonth_type23_max_cnt_day
102: last_3_bhmonth_type23_max_cnt_day_dawn
103: last_3_bhmonth_type23_max_cnt_hour
104: last_3_bhmonth_type23_mean_cnt_day
105: last_3_bhmonth_type23_mean_cnt_day_dawn
106: last_3_bhmonth_type23_mean_cnt_hour
107: last_3_bhmonth_type23_min_cnt_day
108: last_3_bhmonth_type23_std_cnt_day
109: last_3_bhmonth_type23_std_cnt_day_dawn
110: last_3_bhmonth_type23_std_cnt_hour
111: last_6_bhmonth_type1_cnt
112: last_6_bhmonth_type1_dawn_click_pct
113: last_6_bhmonth_type1_max_click_cnt_day
114: last_6_bhmonth_type1_max_cnt_day
115: last_6_bhmonth_type1_max_cnt_day_dawn
116: last_6_bhmonth_type1_max_cnt_hour
117: last_6_bhmonth_type1_mean_cnt_day
118: last_6_bhmonth_type1_mean_cnt_day_dawn
119: last_6_bhmonth_type1_mean_cnt_hour
120: last_6_bhmonth_type1_min_cnt_day
121: last_6_bhmonth_type1_std_cnt_day
122: last_6_bhmonth_type1_std_cnt_day_dawn
123: last_6_bhmonth_type1_std_cnt_hour
124: last_6_bhmonth_type23_cnt
125: last_6_bhmonth_type23_dawn_click_pct
126: last_6_bhmonth_type23_max_click_cnt_day
127: last_6_bhmonth_type23_max_cnt_day
128: last_6_bhmonth_type23_max_cnt_day_dawn
129: last_6_bhmonth_type23_max_cnt_hour
130: last_6_bhmonth_type23_mean_cnt_day
131: last_6_bhmonth_type23_mean_cnt_day_dawn
132: last_6_bhmonth_type23_mean_cnt_hour
133: last_6_bhmonth_type23_min_cnt_day
134: last_6_bhmonth_type23_std_cnt_day
135: last_6_bhmonth_type23_std_cnt_day_dawn
136: last_6_bhmonth_type23_std_cnt_hour
137: max_month_diff
138: mean_month_diff
139: min_month_diff
140: sum_month_diff
141: gender
142: age
143: cell_province
144: id_province
145: id_city
146: max_interval
147: reg_interval
148: cell_change
149: listing_num_12m
150: listing_num_24m
151: listing_num_6m
152: max_interset_per_12m
153: max_interset_per_24m
154: max_interset_per_6m
155: max_listing_per_day_12m
156: max_listing_per_day_24m
157: max_listing_per_day_6m
158: max_listing_per_month_12m
159: max_listing_per_month_24m
160: max_listing_per_month_6m
161: max_principal_12m
162: max_principal_24m
163: max_principal_6m
164: max_rate_12m
165: max_rate_24m
166: max_rate_6m
167: max_term_12m
168: max_term_24m
169: max_term_6m
170: mean_interset_per_12m
171: mean_interset_per_24m
172: mean_interset_per_6m
173: mean_principal_12m
174: mean_principal_24m
175: mean_principal_6m
176: mean_rate_12m
177: mean_rate_24m
178: mean_rate_6m
179: mean_term_12m
180: mean_term_24m
181: mean_term_6m
182: min_interset_per_12m
183: min_interset_per_24m
184: min_interset_per_6m
185: min_principal_12m
186: min_principal_24m
187: min_principal_6m
188: min_rate_12m
189: min_rate_24m
190: min_rate_6m
191: min_term_12m
192: min_term_24m
193: min_term_6m
194: sum_interset_per_12m
195: sum_interset_per_24m
196: sum_interset_per_6m
197: sum_principal_12m
198: sum_principal_24m
199: sum_principal_6m
200: tag_cnt
201: tag_list
202: due_date_weekday

